"""
Django settings for omni_stock project.

Generated by 'django-admin startproject' using Django 5.0.6.
"""
import os
from pathlib import Path
from datetime import timedelta 
import environ


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Minimal env helper to avoid requiring the "environ" package.
# This will read a local .env file into os.environ (if present) and provide
# env(...) and env.bool(...) compatible calls used below.

# Read the .env file if it exists (for local debugging outside of Docker)
# In Docker, the variables are passed directly from docker-compose.yml, but this is safe.
_env_path = os.path.join(BASE_DIR.parent, '.env')
if os.path.exists(_env_path):
    with open(_env_path, encoding='utf-8') as _f:
        for _line in _f:
            _line = _line.strip()
            if not _line or _line.startswith('#'):
                continue
            if '=' in _line:
                _k, _v = _line.split('=', 1)
                _k = _k.strip()
                _v = _v.strip().strip('"').strip("'")
                # Don't overwrite existing environment variables
                os.environ.setdefault(_k, _v)

def _parse_bool(value, default=False):
    if value is None:
        return bool(default)
    return str(value).strip().lower() in ('1', 'true', 'yes', 'y', 'on')

class SimpleEnv:
    def __call__(self, name, default=None):
        return os.environ.get(name, default)
    def bool(self, name, default=False):
        return _parse_bool(os.environ.get(name), default)

env = SimpleEnv()


# SECURITY WARNING: keep the secret key used in production secret!
# Use the DJANGO_SECRET_KEY environment variable defined in .env.
# For local development only, we allow a fallback value if DEBUG is True.
SECRET_KEY = env('DJANGO_SECRET_KEY', default='django-insecure-default-fallback-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=True)

# Fail fast if running in non-debug mode without a proper secret key.
if not DEBUG and (not SECRET_KEY or SECRET_KEY == 'django-insecure-default-fallback-key'):
    raise RuntimeError('DJANGO_SECRET_KEY must be set when DEBUG is False. Set it in your .env file.')

ALLOWED_HOSTS = ['*'] # Allow connections from Docker network/host


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party Apps
    'rest_framework',
    'rest_framework_simplejwt', 
    # Third-party utilities
    'corsheaders',
    'admin_thumbnails',
    'drf_spectacular',
    # Local Apps 
    'collectibles', 
]

MIDDLEWARE = [
    # CORS middleware should be placed as high as possible
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS: allow requests from frontend during development. For production,
# set specific origins via CORS_ALLOWED_ORIGINS.
# Allow only local frontend (e.g., React at localhost:3000) during development
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
# Alternatively, to allow all localhost ports, use:
# CORS_ALLOWED_ORIGIN_REGEXES = [r"^https?://(localhost|127\.0\.0\.1):\d+$"]

ROOT_URLCONF = 'omni_stock.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'omni_stock.wsgi.application'


# Database Configuration
# This is where we dynamically set the database based on environment variables
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('POSTGRES_DB'),
        'USER': env('POSTGRES_USER'),
        'PASSWORD': env('POSTGRES_PASSWORD'),
        'HOST': env('POSTGRES_HOST'), # This must be 'db', the service name in docker-compose.yml
        'PORT': env('POSTGRES_PORT'),
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# Use leading slashes for URL settings so `static()` and other helpers
# generate correct URL patterns. Define MEDIA settings to avoid adding a
# catch-all static pattern when MEDIA_URL is missing.
STATIC_URL = '/static/'

# Media files (user-uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    # Set JWT as the default authentication class globally
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Set the default permissions to allow unauthenticated access for now.
    # We will change this to IsAuthenticated later in the roadmap (P3.4)
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),

    # Use drf-spectacular for schema generation when installed
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema'
}

# Optional drf-spectacular settings can be added here if needed later
# SPECTACULAR_SETTINGS = {
# }

SIMPLE_JWT = {
    # JWT lifespan settings
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}