# Generated by Django 5.0.6 on 2025-11-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0007_add_carddetails_btree_indexes_concurrent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.RemoveIndex(
            model_name='carddetails',
            name='carddetails_language_lwr_idx',
        ),
        migrations.RemoveIndex(
            model_name='carddetails',
            name='carddetails_market_lwr_idx',
        ),
        migrations.RemoveIndex(
            model_name='carddetails',
            name='carddetails_language_btree_idx',
        ),
        migrations.RemoveIndex(
            model_name='carddetails',
            name='carddetails_market_btree_idx',
        ),
        migrations.RemoveField(
            model_name='collectible',
            name='image',
        ),
        migrations.AddField(
            model_name='collectible',
            name='image_url',
            field=models.URLField(blank=True, help_text='Public image URL stored in Supabase.', null=True),
        ),
    ]
