# Generated by Django 5.0.6 on 2025-11-24 20:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0008_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectible',
            old_name='current_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='collectible',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='collectible',
            name='location',
        ),
        migrations.AddField(
            model_name='collectible',
            name='category',
            field=models.CharField(blank=True, help_text='High-level category (e.g., TCG, Video Games, Collectibles).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collectible',
            name='condition',
            field=models.CharField(blank=True, help_text='Human-readable condition (e.g., Mint, Near Mint).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collectible',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
