# Generated by Django 5.0.6 on 2025-11-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0009_collectible_schema_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text="User's profile picture", null=True, upload_to='profile_pictures/'),
        ),
    ]
