# Generated by Django 5.0.6 on 2025-12-09 00:26

import backend.users.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0010_add_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text="User's profile picture (max 5MB, JPEG/PNG/GIF/WebP only)", null=True, upload_to='profile_pictures/', validators=[backend.users.validators.ImageFileValidator(), backend.users.validators.FileSizeValidator(max_mb=5)]),
        ),
        migrations.CreateModel(
            name='InventoryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Public URL of the media file.')),
                ('media_type', models.CharField(choices=[('primary', 'Primary Image'), ('gallery', 'Gallery Image')], default='gallery', help_text='Classify this media (primary vs gallery).', max_length=32)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order of media files for display purposes.')),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this media is the primary display image.')),
                ('width', models.PositiveIntegerField(blank=True, help_text='Width of the media in pixels (if applicable).', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Height of the media in pixels (if applicable).', null=True)),
                ('size_kb', models.PositiveIntegerField(blank=True, help_text='Size of the media file in kilobytes.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the media')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='collectibles.collectible')),
            ],
            options={
                'unique_together': {('item', 'sort_order')},
            },
        ),
    ]
