# Generated by Django 5.0.6 on 2025-12-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0012_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.URLField(blank=True, help_text="User's profile picture URL (stored in Supabase)", null=True),
        ),
    ]
