# Generated by Django 5.0.6 on 2025-12-11 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0013_alter_userprofile_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, choices=[('retail', 'Retail'), ('online', 'Online'), ('popup', 'Pop-up'), ('warehouse', 'Warehouse')], max_length=32, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('banner_url', models.URLField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=8, null=True)),
                ('default_tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='collectibles.vendor')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('vendor', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(help_text='Quantity change (positive or negative).')),
                ('reason', models.CharField(blank=True, max_length=64, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collectible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='collectibles.collectible')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_actions', to=settings.AUTH_USER_MODEL)),
                ('from_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_out', to='collectibles.store')),
                ('to_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_in', to='collectibles.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='collectible',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Store that currently stocks this item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectibles', to='collectibles.store'),
        ),
        migrations.CreateModel(
            name='VendorMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('member', 'Member'), ('staff', 'Staff'), ('billing', 'Billing'), ('viewer', 'Viewer')], default='member', max_length=32)),
                ('title', models.CharField(blank=True, help_text='Optional display title for rosters (e.g., Lead Buyer).', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('invite_code', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_memberships', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='collectibles.vendor')),
            ],
            options={
                'ordering': ['vendor_id', 'user_id'],
                'unique_together': {('vendor', 'user')},
            },
        ),
        migrations.CreateModel(
            name='StoreAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('sales', 'Sales'), ('view_only', 'View Only')], default='sales', max_length=32)),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='Optional custom overrides (e.g., can_adjust_price).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='collectibles.store')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_access', to='collectibles.vendormember')),
            ],
            options={
                'ordering': ['store_id', 'member_id'],
                'unique_together': {('store', 'member')},
            },
        ),
    ]
