# Generated by Django 5.0.6 on 2025-12-17 04:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collectibles", "0015_collectible_store_not_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendormember",
            name="invite_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("revoked", "Revoked"),
                ],
                default="pending",
                help_text="Lifecycle state for invitations and membership activation.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vendormember",
            name="invited_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="vendormember",
            name="responded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendormember",
            name="revoked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
