# Generated by Django 5.0.6 on 2025-12-23 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0021_remove_userprofile_vendor_add_vendormember_is_primary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardmetadata',
            options={'verbose_name': 'Card Metadata', 'verbose_name_plural': 'Card Metadata'},
        ),
        migrations.AlterModelOptions(
            name='catalogitem',
            options={'ordering': ['name'], 'verbose_name': 'Catalog Item', 'verbose_name_plural': 'Catalog Items'},
        ),
        migrations.RemoveField(
            model_name='stockledger',
            name='delta',
        ),
        migrations.RemoveField(
            model_name='stockledger',
            name='from_store',
        ),
        migrations.RemoveField(
            model_name='stockledger',
            name='performed_by',
        ),
        migrations.RemoveField(
            model_name='stockledger',
            name='to_store',
        ),
        migrations.AddField(
            model_name='cardmetadata',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cardmetadata',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cardmetadata',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cardmetadata',
            name='completeness',
            field=models.CharField(blank=True, choices=[('loose', 'Loose'), ('cib', 'CIB'), ('sealed', 'Sealed'), ('box_manual', 'Box & Manual')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cardmetadata',
            name='finish',
            field=models.CharField(blank=True, choices=[('non_holo', 'Non-Holo'), ('holo', 'Holo'), ('reverse_holo', 'Reverse Holo'), ('full_art', 'Full Art')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cardmetadata',
            name='game_genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cardmetadata',
            name='game_region',
            field=models.CharField(blank=True, choices=[('ntsc_u', 'NTSC-U'), ('ntsc_j', 'NTSC-J'), ('pal', 'PAL'), ('region_free', 'Region Free')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cardmetadata',
            name='material',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cardmetadata',
            name='platform',
            field=models.CharField(blank=True, choices=[('nintendo_switch', 'Nintendo Switch'), ('ps5', 'PlayStation 5'), ('xbox_series_x', 'Xbox Series X'), ('pc', 'PC'), ('retro', 'Retro'), ('handheld', 'Handheld')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cardmetadata',
            name='rarity',
            field=models.CharField(blank=True, choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('ultra_rare', 'Ultra Rare'), ('secret_rare', 'Secret Rare')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cardmetadata',
            name='set_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cardmetadata',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='search_text',
            field=models.TextField(blank=True, db_index=True, help_text='Denormalized search field (name + sku + description).'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('low_stock', 'Low Stock'), ('archived', 'Archived')], db_index=True, default='active', help_text='Lifecycle flag for quick filtering (UI + reports).', max_length=20),
        ),
        migrations.AddField(
            model_name='catalogvariant',
            name='media',
            field=models.ManyToManyField(blank=True, help_text='Optional images tied to this variant/condition.', related_name='variants', to='collectibles.catalogmedia'),
        ),
        migrations.AddField(
            model_name='catalogvariant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional variant-specific price override.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_ledger_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='quantity_after',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='quantity_before',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='quantity_delta',
            field=models.IntegerField(default=0, help_text='Positive for adds, negative for removals.'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='related_sale_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='transaction_type',
            field=models.CharField(choices=[('add', 'Added to Inventory'), ('remove', 'Removed from Inventory'), ('adjustment', 'Adjustment'), ('sale', 'Sold'), ('transfer', 'Transferred'), ('write_off', 'Write Off')], default='adjustment', max_length=20),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cardmetadata',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_metadata', to='collectibles.catalogitem'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='category',
            field=models.CharField(blank=True, choices=[('pokemon_card', 'Pokémon Card'), ('clothing', 'Clothing'), ('video_game', 'Video Game'), ('other', 'Other Collectible')], db_index=True, help_text='High-level category used for polymorphic attributes.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['vendor', 'store'], name='catalog_ite_vendor__0b6c03_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['vendor', 'category'], name='catalog_ite_vendor__3cf1ce_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['store', 'category'], name='catalog_ite_store_i_48f341_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['name'], name='catalog_ite_name_9b7e7e_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['sku'], name='catalog_ite_sku_0b70c9_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['search_text'], name='catalog_ite_search__f119f3_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['category', 'created_at'], name='catalog_ite_categor_01f166_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['vendor', '-created_at'], name='catalog_ite_vendor__241ccf_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['item', 'created_at'], name='collectible_item_id_77cf78_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['transaction_type', 'created_at'], name='collectible_transac_bb146e_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['vendor', 'is_active'], name='org_store_vendor__03925d_idx'),
        ),
        migrations.AddIndex(
            model_name='vendormember',
            index=models.Index(fields=['vendor', 'user', 'is_active'], name='org_members_vendor__0f537a_idx'),
        ),
        migrations.AddIndex(
            model_name='vendormember',
            index=models.Index(fields=['user', 'is_primary'], name='org_members_user_id_532b7a_idx'),
        ),
    ]
