# Generated by Django 5.0.6 on 2026-01-29 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collectibles", "0022_alter_cardmetadata_options_alter_catalogitem_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accessory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(help_text="e.g. Binder, Sleeve, Deck Box", max_length=100),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Accessories",
            },
        ),
        migrations.CreateModel(
            name="Era",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("start_year", models.IntegerField(blank=True, null=True)),
                ("end_year", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("booster_pack", "Booster Pack"),
                            ("booster_box", "Booster Box"),
                            ("etb", "Elite Trainer Box"),
                            ("theme_deck", "Theme Deck"),
                            ("tin", "Tin"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("release_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="catalogitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="The retail product this item came from (optional).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collectibles",
                to="collectibles.product",
            ),
        ),
        migrations.CreateModel(
            name="Set",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(help_text="e.g. SWSH01", max_length=50, unique=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("card_count", models.IntegerField(default=0)),
                (
                    "era",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="collectibles.era",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="collectibles.set",
            ),
        ),
    ]
