#!/bin/bash
set -euo pipefail

# generate-summary.sh
# Generates a comprehensive, visually appealing CI report in Markdown format.
# It parses test results and coverage reports from both backend and frontend,
# includes links to artifacts, and provides a placeholder for deployment previews.

# --- Configuration and Helpers ---
ARTIFACTS_DIR="artifacts"
SUMMARY_TITLE="### 🧪 Omni-Stock CI Report 🧪"
SUMMARY_FOOTER="---\n*This report was auto-generated by the CI workflow.*"

# Function to safely get a value from XML using yq, returns default if error
get_xml_attr() {
  local file=$1
  local query=$2
  local default=$3
  yq -p xml "$query" "$file" 2>/dev/null || echo "$default"
}

# --- Header ---
SUMMARY="$SUMMARY_TITLE\n\n"
SUMMARY+="A summary of the test runs, code coverage, and other checks for this pull request.\n\n"

# --- Backend Summary ---
BACKEND_SUMMARY="<details open><summary><strong>🚀 Backend Results (Pytest)</strong></summary>\n\n"
backend_reports_found=0
for report in $(find "$ARTIFACTS_DIR" -name "pytest-report-*.xml" 2>/dev/null || true); do
  backend_reports_found=1
  PYTHON_VERSION=$(echo "$report" | sed -n 's/.*backend-pytest-report-\([0-9.]*\)\/pytest-report.xml/\1/p')
  [ -z "$PYTHON_VERSION" ] && PYTHON_VERSION="Unknown"
  
  TESTS=$(get_xml_attr "$report" '.testsuite."@tests"' 0)
  FAILURES=$(get_xml_attr "$report" '.testsuite."@failures"' 0)
  ERRORS=$(get_xml_attr "$report" '.testsuite."@errors"' 0)
  SKIPPED=$(get_xml_attr "$report" '.testsuite."@skipped"' 0)
  PASSED=$((TESTS - FAILURES - ERRORS - SKIPPED))
  
  # Coverage
  COVERAGE_FILE=$(find "$(dirname "$report")" -name "coverage.xml" 2>/dev/null || true)
  COVERAGE_PERCENT="N/A"
  if [ -f "$COVERAGE_FILE" ]; then
    LINE_RATE=$(get_xml_attr "$COVERAGE_FILE" '.coverage."@line-rate"' 0)
    COVERAGE_PERCENT=$(printf "%.2f%%" $(echo "$LINE_RATE * 100" | bc))
  fi

  BACKEND_SUMMARY+="**Python ${PYTHON_VERSION}**\n"
  BACKEND_SUMMARY+="| Total Tests | Passed ✅ | Failed ❌ | Errors ❗ | Skipped ⏭️ | Coverage 📊 |\n"
  BACKEND_SUMMARY+="| :---: | :---: | :---: | :---: | :---: | :---: |\n"
  BACKEND_SUMMARY+="| **${TESTS}** | ${PASSED} | ${FAILURES} | ${ERRORS} | ${SKIPPED} | **${COVERAGE_PERCENT}** |\n\n"
done

if [ $backend_reports_found -eq 0 ]; then
  BACKEND_SUMMARY+="*No backend test reports found.*\n"
fi
BACKEND_SUMMARY+="</details>"

# --- Frontend Summary ---
FRONTEND_SUMMARY="<details open><summary><strong>🎨 Frontend Results (Vitest)</strong></summary>\n\n"
FRONTEND_REPORT=$(find "$ARTIFACTS_DIR" -name "test-results.json" 2>/dev/null || true)
if [ -f "$FRONTEND_REPORT" ]; then
  NUM_TEST_SUITES=$(jq '.numTotalTestSuites' "$FRONTEND_REPORT")
  PASSED_SUITES=$(jq '.numPassedTestSuites' "$FRONTEND_REPORT")
  FAILED_SUITES=$(jq '.numFailedTestSuites' "$FRONTEND_REPORT")
  TOTAL_TESTS=$(jq '.numTotalTests' "$FRONTEND_REPORT")
  PASSED_TESTS=$(jq '.numPassedTests' "$FRONTEND_REPORT")
  FAILED_TESTS=$(jq '.numFailedTests' "$FRONTEND_REPORT")
  
  # Frontend Coverage from lcov.info
  LCOV_FILE=$(find "$ARTIFACTS_DIR" -name "lcov.info" 2>/dev/null || true)
  FRONTEND_COVERAGE="N/A"
  if [ -f "$LCOV_FILE" ]; then
    # Extract lines hit (LH) and lines found (LF)
    LCOV_SUMMARY=$(grep -E "^LH:|^LF:" "$LCOV_FILE" | tr '\n' ' ')
    LINES_HIT=$(echo "$LCOV_SUMMARY" | sed -n 's/.*LH:\([0-9]*\).*/\1/p')
    LINES_FOUND=$(echo "$LCOV_SUMMARY" | sed -n 's/.*LF:\([0-9]*\).*/\1/p')
    if [ -n "$LINES_FOUND" ] && [ "$LINES_FOUND" -gt 0 ]; then
      FRONTEND_COVERAGE=$(printf "%.2f%%" $(echo "scale=4; $LINES_HIT / $LINES_FOUND * 100" | bc))
    fi
  fi

  FRONTEND_SUMMARY+="| Metric | Count |\n"
  FRONTEND_SUMMARY+="| :--- | :---: |\n"
  FRONTEND_SUMMARY+="| Test Suites | **${NUM_TEST_SUITES}** (${PASSED_SUITES} passed, ${FAILED_SUITES} failed) |\n"
  FRONTEND_SUMMARY+="| Total Tests | **${TOTAL_TESTS}** (${PASSED_TESTS} passed, ${FAILED_TESTS} failed) |\n"
  FRONTEND_SUMMARY+="| Code Coverage 📊 | **${FRONTEND_COVERAGE}** |\n"
else
  FRONTEND_SUMMARY+="*No frontend test report found.*\n"
fi
FRONTEND_SUMMARY+="\n</details>"

# --- Deployment Preview Section ---
DEPLOYMENT_SUMMARY="<details><summary><strong>🌐 Deployment Previews</strong></summary>\n\n"
if [ -n "${PREVIEW_URL-}" ]; then
    DEPLOYMENT_SUMMARY+="🚀 **Frontend Preview:** [${PREVIEW_URL}](${PREVIEW_URL})\n"
    # Add backend link if available
    # DEPLOYMENT_SUMMARY+="📦 **Backend Preview:** [${BACKEND_PREVIEW_URL}](${BACKEND_PREVIEW_URL})\n"
else
    DEPLOYMENT_SUMMARY+="*No preview deployment URL was provided for this PR.*\n\n"
  DEPLOYMENT_SUMMARY+="To enable, set the \`PREVIEW_URL\` repository secret or configure your deployment provider (e.g., Vercel, Render) to post a deployment status.\n"
fi
DEPLOYMENT_SUMMARY+="</details>"

# --- Artifacts Section ---
ARTIFACTS_SUMMARY="<details><summary><strong>🗂️ Downloadable Artifacts</strong></summary>\n\n"
ARTIFACTS_SUMMARY+="The following reports and logs were generated during the CI run. You can download them from the 'Artifacts' section of the [Actions summary page](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}).\n\n"
for artifact_dir in $(find "$ARTIFACTS_DIR" -mindepth 1 -maxdepth 1 -type d); do
  ARTIFACTS_SUMMARY+="- **$(basename "$artifact_dir")**\n"
done
ARTIFACTS_SUMMARY+="</details>"


# --- Assemble Final Report ---
SUMMARY+="$BACKEND_SUMMARY\n\n$FRONTEND_SUMMARY\n\n$DEPLOYMENT_SUMMARY\n\n$ARTIFACTS_SUMMARY\n\n$SUMMARY_FOOTER"

# Set GitHub Actions output
if [ -n "${GITHUB_OUTPUT-}" ]; then
  # Escape backticks in SUMMARY so the value can be safely embedded inside
  # a JavaScript template literal (used by actions/github-script) without
  # causing a SyntaxError: Unexpected identifier 'PREVIEW_URL'.
  echo "summary_body<<EOF" >> "$GITHUB_OUTPUT"
  # Use printf + sed to replace ` with \` (escaped backtick).
  printf '%s' "$SUMMARY" | sed 's/`/\\`/g' >> "$GITHUB_OUTPUT"
  echo "EOF" >> "$GITHUB_OUTPUT"
else
  # Fallback for local execution
  echo -e "$SUMMARY"
fi
