# Generated by Django 5.0.6 on 2025-12-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0011_alter_userprofile_profile_picture_inventorymedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.URLField(blank=True, help_text="Public URL of the user's profile picture (stored in Supabase).", null=True),
        ),
    ]
