# Generated by Django 5.0.6 on 2025-12-10 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0013_alter_userprofile_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, choices=[('online', 'Online'), ('retail', 'Retail'), ('popup', 'Pop-up'), ('warehouse', 'Warehouse')], max_length=32, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, help_text='Optional physical address or pickup notes.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('banner_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='collectibles.vendor')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'ordering': ['name'],
                'unique_together': {('vendor', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='VendorMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('solo', 'Solo')], default='solo', help_text='High-level vendor role used for invitations and permissions.', max_length=32)),
                ('title', models.CharField(blank=True, help_text='Optional title shown in team rosters.', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_memberships', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='collectibles.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Member',
                'verbose_name_plural': 'Vendor Members',
            },
        ),
        migrations.CreateModel(
            name='StoreAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('sales', 'Sales'), ('view_only', 'View Only')], default='sales', max_length=32)),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='Custom overrides (e.g., can_adjust_price).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='collectibles.store')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_accesses', to='collectibles.vendormember')),
            ],
            options={
                'verbose_name': 'Store Access',
                'verbose_name_plural': 'Store Access',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Supabase-hosted image URL.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('size_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='collectibles.collectible')),
            ],
            options={
                'ordering': ['product_id', 'sort_order', 'id'],
                'unique_together': {('product', 'sort_order')},
            },
        ),
        migrations.AddIndex(
            model_name='vendormember',
            index=models.Index(fields=['vendor', 'role'], name='collectible_vendor__2b8ec8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storeaccess',
            unique_together={('store', 'member')},
        ),
    ]
