# Generated by Django 5.0.6 on 2025-12-11

import django.db.models.deletion
from django.db import migrations, models

DEFAULT_STORE_NAME = "Default Store"


def ensure_store_relationships(apps, schema_editor):
    Vendor = apps.get_model("collectibles", "Vendor")
    Store = apps.get_model("collectibles", "Store")
    Collectible = apps.get_model("collectibles", "Collectible")

    vendor_store_map = {}

    for vendor in Vendor.objects.all().iterator():
        store = Store.objects.filter(vendor=vendor).order_by("id").first()
        if store is None:
            store = Store.objects.create(
                vendor=vendor,
                name=DEFAULT_STORE_NAME,
                metadata={"auto_created": True},
            )
        vendor_store_map[vendor.id] = store.id

    missing_store_qs = Collectible.objects.filter(store__isnull=True, vendor__isnull=False).values_list(
        "id", "vendor_id"
    )
    for collectible_id, vendor_id in missing_store_qs.iterator():
        store_id = vendor_store_map.get(vendor_id)
        if store_id is None:
            continue
        Collectible.objects.filter(pk=collectible_id).update(store_id=store_id)


class Migration(migrations.Migration):

    dependencies = [
        ("collectibles", "0014_store_stockledger_collectible_store_vendormember_and_more"),
    ]

    operations = [
        migrations.RunPython(ensure_store_relationships, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="collectible",
            name="store",
            field=models.ForeignKey(
                help_text="Store that currently stocks this item.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="collectibles",
                to="collectibles.store",
            ),
        ),
    ]
