# Generated by Django 5.0.6 on 2025-12-17 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collectibles", "0015_collectible_store_not_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendormember",
            name="active_store",
            field=models.ForeignKey(
                blank=True,
                help_text="Last store selected by this member for the vendor.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_members",
                to="collectibles.store",
            ),
        ),
    ]
