# Generated by Django 5.0.6 on 2025-12-04 03:50

import backend.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, help_text='Birthdate (used for age verification).', null=True, validators=[backend.users.validators.validate_birthdate]),
        ),
        migrations.AddField(
            model_name='user',
            name='company_code',
            field=models.CharField(blank=True, help_text='Optional invite code to link this user to an existing company.', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, help_text='Display name for the vendor or company.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_site',
            field=models.URLField(blank=True, help_text='Public website for the company (optional).', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number in E.164 format.', max_length=20, null=True, validators=[backend.users.validators.validate_phone_number]),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_completed',
            field=models.BooleanField(default=False, help_text='Indicates whether the user has finished the onboarding form.'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('vendor_manager', 'Vendor Manager'), ('staff', 'Staff'), ('solo', 'Solo'), ('viewer', 'Viewer')], default='solo', help_text="Controls the user's permissions within a company.", max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='tos_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the user accepted terms of service.', null=True),
        ),
    ]
