# Generated by Django 5.0.6 on 2025-12-09 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_birthdate_user_company_code_user_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('profile_avatar', 'Profile Avatar'), ('vendor_logo', 'Vendor Logo'), ('storefront_banner', 'Storefront Banner'), ('user_banner', 'User Banner')], max_length=32)),
                ('url', models.URLField(help_text='URL of the uploaded media file.')),
                ('width', models.PositiveIntegerField(blank=True, help_text='Width of the media in pixels (if applicable).', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Height of the media in pixels (if applicable).', null=True)),
                ('size_kb', models.PositiveIntegerField(blank=True, help_text='Size of the media file in kilobytes.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the media (JSON string ok).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
