# Generated by Django 5.0.6 on 2025-12-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usermedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermedia',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata about the media'),
        ),
    ]
