# Generated by Django 5.0.6 on 2025-12-10 04:11

from django.db import migrations, models


def _populate_entity_ids(apps, schema_editor):
    UserMedia = apps.get_model("users", "UserMedia")
    for media in UserMedia.objects.filter(entity_id__isnull=True, entity_type="user"):
        media.entity_id = media.user_id
        media.save(update_fields=["entity_id"])


def _reset_entity_ids(apps, schema_editor):
    UserMedia = apps.get_model("users", "UserMedia")
    UserMedia.objects.update(entity_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usermedia_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermedia',
            name='entity_id',
            field=models.PositiveBigIntegerField(blank=True, help_text='Identifier for the related entity (user/vendor/store/product).', null=True),
        ),
        migrations.AddField(
            model_name='usermedia',
            name='entity_type',
            field=models.CharField(choices=[('user', 'User'), ('vendor', 'Vendor'), ('store', 'Store'), ('product', 'Product')], default='user', help_text='Which domain object this media belongs to.', max_length=32),
        ),
        migrations.RunPython(_populate_entity_ids, _reset_entity_ids),
        migrations.AlterUniqueTogether(
            name='usermedia',
            unique_together={('user', 'entity_type', 'entity_id', 'media_type')},
        ),
        migrations.AddIndex(
            model_name='usermedia',
            index=models.Index(fields=['entity_type', 'entity_id'], name='users_userm_entity__543948_idx'),
        ),
    ]
