# Generated by Django 5.0.6 on 2025-11-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collectible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The common name of the collectible item.', max_length=255)),
                ('sku', models.CharField(help_text='Stock Keeping Unit (Unique Identifier).', max_length=50, unique=True)),
                ('quantity', models.IntegerField(default=0, help_text='Current number of units in stock.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Collectible Item',
                'verbose_name_plural': 'Collectible Items',
                'ordering': ['name'],
            },
        ),
    ]
