# Generated by Django 5.0.6 on 2025-11-10 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectible',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The current market value or selling price.', max_digits=10),
        ),
        migrations.AddField(
            model_name='collectible',
            name='image',
            field=models.ImageField(blank=True, help_text='Image of the collectible item.', null=True, upload_to='collectibles_images/'),
        ),
        migrations.AddField(
            model_name='collectible',
            name='intake_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The price paid for the item (cost basis).', max_digits=10),
        ),
        migrations.AddField(
            model_name='collectible',
            name='location',
            field=models.CharField(blank=True, help_text="Physical location (e.g., 'Binder 3', 'Shelf A')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collectible',
            name='projected_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The projected price based on market trends.', max_digits=10),
        ),
        migrations.AddField(
            model_name='collectible',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user/vendor who owns this inventory item.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
