# Generated by Django 5.0.6 on 2025-11-11 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0002_collectible_current_price_collectible_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_info', models.TextField(blank=True, help_text='Free-form contact metadata (JSON string ok).', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CardDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psa_grade', models.DecimalField(blank=True, decimal_places=1, help_text='Numeric grade, e.g. 8.5 or 10.0', max_digits=3, null=True)),
                ('condition', models.CharField(blank=True, help_text='Human-readable condition (e.g., Mint, Near Mint).', max_length=50, null=True)),
                ('external_ids', models.TextField(blank=True, help_text='JSON string of external IDs (portable across DBs)', null=True)),
                ('last_estimated_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('print_run', models.CharField(blank=True, help_text='Optional print run or edition info.', max_length=100, null=True)),
                ('market_region', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the card', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collectible', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_details', to='collectibles.collectible')),
            ],
            options={
                'verbose_name': 'Card Details',
                'verbose_name_plural': 'Card Details',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=40, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('metadata', models.TextField(blank=True, help_text='Arbitrary profile metadata (JSON string ok).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='collectibles.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='collectible',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectibles', to='collectibles.vendor'),
        ),
    ]
